### ISSUE TITLE
tls 连接 身份认证

### ISSUE THREAD

**Issue by cwy1996** [gaecfov/pulsar-console#1]
pulsar开始前tls身份认证

https实例添加后，无配置书写认证文件等，如下报错：
![image](https://github.com/user-attachments/assets/6225f988-3852-4162-b034-a41665487b3f)

**Comment by gaecfov** [comment]
@cwy1996 已支持TLS和授权认证

**Comment by cwy1996** [comment]
非常感谢，不过密码修改后，修改的密码会被""包裹

例如：123456      实际登录密码为"123456"

**Comment by gaecfov** [comment]
> 非常感谢，不过密码修改后，修改的密码会被""包裹
> 
> 例如：123456 实际登录密码为"123456"

我试了下是正常的，能复现吗？

**Comment by cwy1996** [comment]
![image](https://github.com/user-attachments/assets/a9fa1a5b-8300-4c5e-b168-9023ead19ac8)
![image](https://github.com/user-attachments/assets/1aee24ff-dd31-48bc-91c3-081ab8f858d6)

**Comment by cwy1996** [comment]
![image](https://github.com/user-attachments/assets/e01d1c29-5f52-414d-b509-1390c2ef8d27)

单纯数字可以，试了下组合类型就会带双引号
