### ISSUE TITLE
订阅者很多，希望补充订阅者列表，然后反向查看订阅者的topic

### ISSUE THREAD

**Issue by sunhhw** [gaecfov/pulsar-console#2]
订阅者很多，希望补充订阅者列表，然后反向查看订阅者的topic

**Comment by gaecfov** [comment]
pulsar 的订阅是依附于topic的，如果需要反查，需要把订阅关系落库，可能需要遍历所有 topic 或者监控 zk

**Comment by gaecfov** [comment]
已增加手工同步 namespace 下的订阅关系
